# Site settings
title: Oliur | Music Jekyll blog
description: "A musical website."
url: "http://mereka.github.oi/maintain-a-pc/"
author:
  name: "Zabir aktar"
  email: "zabir.aktar@gmail.com"
  url: "http://mereka.github.oi/maintain-a-pc/"

# Build settings
baseurl: /music-of-oliur/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_pathS: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
